
class ResponseCodes:
    # general response codes
    SERVER_ERROR = "SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR",
    RETRIEVE_SUCCESS = "RETRIEVE_SUCCESS"
    DOES_NOT_EXIST = "DOES_NOT_EXIST"
    DELETED = "DELETED"
    
    # accounts response codes
    # customer response codes
    CUSTOMER_CREATED = "CUSTOMER_CREATED"
    CUSTOMER_ALREADY_EXISTS = "CUSTOMER_ALREADY_EXISTS"
    CUSTOMER_NAME_UPDATED = "CUSTOMER_NAME_UPDATED"
    CUSTOMER_DOES_NOT_EXIST = "CUSTOMER_DOES_NOT_EXIST"
    
    
    # measurement response codes
    MEASUREMENT_TYPE_CREATED = "MEASUREMENT_TYPE_CREATED"
    MEASUREMENT_ALREADY_EXISTS = "MEASUREMENT_ALREADY_EXISTS"
    MEASUREMENT_ITEM_TYPE_CREATED = "MEASUREMENT_ITEM_TYPE_CREATED"
    