# Generated by Django 6.0.3 on 2026-05-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verification_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Semkipo Laundry', max_length=120)),
                ('company_phone', models.CharField(blank=True, default='9813694977', max_length=40)),
                ('pan_number', models.CharField(blank=True, default='123456789', max_length=40)),
                ('company_address', models.CharField(blank=True, default='Boudha, Kathmandu, Nepal', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company setting',
                'verbose_name_plural': 'Company settings',
            },
        ),
    ]
