# Generated by Django 6.0.3 on 2026-03-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('secondary_contact', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
