# Generated by Django 6.0.3 on 2026-05-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loyalty_wash_count',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
