# Generated by Django 6.0.3 on 2026-04-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('pk', 'Pickup'), ('d', 'Delivery')], default='pk', max_length=4),
        ),
    ]
