# Generated by Django 6.0.3 on 2026-04-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='ItemType',
            new_name='measurement_type',
        ),
    ]
