# Generated by Django 6.0.3 on 2026-04-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_itemtype_orderitem_measurement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
