# Generated by Django 6.0.3 on 2026-03-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='measurement_items/'),
        ),
    ]
