# Generated by Django 6.0.3 on 2026-03-30 06:55

import measurement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_itemtype_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtype',
            old_name='Measurement_type',
            new_name='measurement_type',
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='measurement_items/', validators=[measurement.models.validate_image]),
        ),
    ]
